language: java

jdk:
  - openjdk8

branches:
  only:
  - development

before_script: 
  - ls -la # this command just prints the contents of the current working directory.

script: 
  - mvn clean package jacoco:report
<<<<<<< HEAD

=======
  - java –jar Design_pattern/target/Design_pattern-0.0.1-SNAPSHOT-jar-with-dependencies.jar ../src/test/resources/TestClass.java regex local  ../output_metrics_file csv
>>>>>>> 9f451caab8eda72cacc31b131d3829e5b8324f90

after_success:
- bash <(curl -s https://codecov.io/bash) -t 1036eb64-2d96-44c6-b132-0dde4e7dfcca
- java –jar Design_pattern-0.0.1-SNAPSHOT-jar-with-dependencies.jar ../src/test/resources/TestClass.java regex local  ../output_metrics_file csv
