  
language: java

jdk:
  - openjdk8

branches:
  only:
  - development

before_script: 
  - ls -la # this command just prints the contents of the current working directory.

script: 
  - mvn clean package jacoco:report

after_success:
- java -jar Design_pattern/target/Design_pattern-0.0.1-SNAPSHOT-jar-with-dependencies.jar Design_pattern/src/test/resources/TestClass.java regex local Design_pattern/target/output_metrics csv
- command 1> Design_pattern/target/output_metrics.csv
- bash <(curl -s https://codecov.io/bash) -t 1036eb64-2d96-44c6-b132-0dde4e7dfcca
- lines=$ ( diff Design_pattern/target/output_metrics.csv Design_pattern/right_output_metrics.csv  | wc -l )
if [ $lines -gt 0 ]; then
    echo "There are differences"
fi

