language: java

jdk:
  - openjdk8

branches:
  only:
  - development

before_script: 
  - cd Unit_Testing
  - ls -la # this command just prints the contents of the current working directory.

script: 
  - mvn clean package jacoco:report coveralls:report cobertura:cobertura 
    # the coveralls:report is required only for the coveralls coverage service
    # the cobertura:cobertura is optional only for advanced coverage reporting and, if exists, is used by CodeCov 

